name: Build and Upload to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Arm64 Docker Image
        run: docker buildx build --platform linux/arm64 -t arm64-image -f Dockerfile --load .
      
      - name: Extract zip file from arm64 container
        run: docker create --name arm64-container arm64-image && docker cp arm64-container:/app/dist/build.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Copy files to the S3 bucket
        run: |
          aws s3 cp ./build.zip s3://${{ secrets.AWS_BUCKET_NAME }}/build.zip